global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'student-monitoring'

scrape_configs:
  # 1. Prometheus (сам себя)
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 2. PostgreSQL Exporter
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres_exporter:9187']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'my_postgresql_db'

  # 3. Node Exporter (Системные метрики)
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'my_laptop'

  # 4. Custom Exporter (для Дашборда 3)
  - job_name: 'custom_api'
    static_configs:
      - targets: ['host.docker.internal:8000'] # ищет скрипт на порту 8000 вашего ноутбука
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'external_apis'